spring:
  application:
    name: demo
  ai:
    model:
      chat: ollama
    ollama:
      chat:
        options:
          model: llama3.2-korean
          temperature: 0.1
      base-url: http://localhost:11434
      embedding:
        options:
          model: mxbai-embed-large
    vectorstore:
      type: pgvector
      pgvector:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 1234
        table-name: document_embeddings
        dimensions: 1024
        similarity: cosine
        initialize-schema: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234




#  ai:
#    openai:
#      base-url: https://api.groq.com/openai
#      api-key: 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
#      chat:
#        options:
#          model: llama3-70b-8192
#          systemMessage: >
#            ??? ?? ???? ???? ???. ??? ??? ?????? ??? ???? ?????.
#          temperature: 0
